#!/bin/env python3

import discord
from dotenv import load_dotenv
from os.path import isfile
from os import getenv
from sys import stderr

def eprint(*args, **kwargs):
    print(*args, file=stderr, **kwargs)

def startsWith(string, char):
    if string[0] == char:
        return True
    return False

def removeFirstChar(string):
    return string[1:]

if not isfile("./.env"):
    eprint("ERROR: could not find file `.env`")
    exit(1)

load_dotenv()
TOKEN = getenv("DISCORD_TOKEN")
GUILD = getenv("DISCORD_GUILD")

client = discord.Client()

@client.event
async def on_ready():
    guild = discord.utils.get(client.guilds, name=GUILD)

    print(
        f'{client.user} is connected to the following guild:\n'
        f'{guild.name}(id: {guild.id})'
    )

    members = '\n - '.join([member.name for member in guild.members])
    print(f'Guild Members (online):\n - {members}')

@client.event
async def on_message(message):
    if message.author == client.user:
        return

    # commands
    if startsWith(message.content, "!"):
        command = removeFirstChar(message.content)
        if command == "ping":
            await message.channel.send("Pong!")
        elif command == "whatIsInNsfw":
            await message.channel.send("Po$$, nu$$$$, and h$$$ai")
        elif command == "cpp":
            await message.channel.send("**Rust**")
        elif command == "rust":
            await message.channel.send("https://rustrecoveryfoundation.neocities.org/")
        elif command == "python":
            await message.channel.send("loading...")
        elif command == "":
            await message.channel.send("")
        else:
            await message.channel.send(f"ERROR: unknown command: `{command}`")


client.run(TOKEN)
